# Generated by Django 5.0.6 on 2024-05-20 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_assignedtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedtask',
            name='current_task_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='current_task_index',
            field=models.IntegerField(default=0),
        ),
    ]
