# Generated by Django 5.0.6 on 2024-05-22 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_assignedtask_current_task_index_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='profile_data_id',
            new_name='profile_data',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='subject_id',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='taskresult',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='taskresult',
            old_name='task_id',
            new_name='task',
        ),
    ]
