# Generated by Django 5.0.6 on 2024-05-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_task_answer_alter_task_topic_alter_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='answer',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='task',
            name='topic',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(max_length=256),
        ),
    ]
