# Generated by Django 5.0.6 on 2024-05-27 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_task_answer_alter_task_topic_alter_task_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=128, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.student')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижение',
            },
        ),
    ]
