# Generated by Django 5.0.6 on 2024-06-13 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_achievement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'verbose_name': 'Достижение', 'verbose_name_plural': 'Достижения'},
        ),
        migrations.AlterModelOptions(
            name='assignedtask',
            options={'verbose_name': 'Назначенную задачу', 'verbose_name_plural': 'Назначенные задачи'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Ученика', 'verbose_name_plural': 'Ученики'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задачу', 'verbose_name_plural': 'Задачи'},
        ),
    ]
