# Generated by Django 5.0.6 on 2024-06-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_achievement_options_alter_assignedtask_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='scale',
            field=models.CharField(choices=[(0, 'GENERAL'), (1, 'INSIDE')], default=0, max_length=12),
            preserve_default=False,
        ),
    ]
