# Generated by Django 5.0.6 on 2024-06-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_rank_task_image_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='image_id',
        ),
        migrations.AddField(
            model_name='task',
            name='image_name',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
