# Generated by Django 5.0.6 on 2024-06-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_remove_task_image_id_task_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
