# Generated by Django 5.0.6 on 2024-06-27 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_achievement_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskresult',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.subject'),
            preserve_default=False,
        ),
    ]
